// Package data for category-based purchases
export const packageData = [
  // Haryana packages
  {
    id: "pkg-haryana-all",
    title: "Haryana Complete Package",
    description: "Complete preparation package for all Haryana state exams with 400 comprehensive tests",
    price: 1600, // 400 tests × 5 rupees = 2000 rupees, with 20% discount = 1600 rupees
    originalPrice: 2000, // Sum of individual test prices
    discount: 20, // Percentage discount
    level: "Beginner to Advanced",
    tests: 400,
    duration: "12 months access",
    category: "haryana",
    testIds: Array.from({ length: 400 }, (_, i) => i + 1), // IDs 1-400
  },
  {
    id: "pkg-haryana-police",
    title: "Haryana Police Exams Package",
    description: "Complete preparation package for Haryana Police exams with 100 comprehensive tests",
    price: 400, // 100 tests × 5 rupees = 500 rupees, with 20% discount = 400 rupees
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "haryana",
    subcategory: "police",
    testIds: Array.from({ length: 100 }, (_, i) => i + 1), // IDs 1-100
  },
  {
    id: "pkg-haryana-teaching",
    title: "Haryana Teaching Exams Package",
    description: "Complete preparation package for Haryana Teaching exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "haryana",
    subcategory: "teaching",
    testIds: Array.from({ length: 100 }, (_, i) => i + 101), // IDs 101-200
  },
  {
    id: "pkg-haryana-clerical",
    title: "Haryana Clerical Exams Package",
    description: "Complete preparation package for Haryana Clerical exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "haryana",
    subcategory: "clerical",
    testIds: Array.from({ length: 100 }, (_, i) => i + 201), // IDs 201-300
  },
  {
    id: "pkg-haryana-technical",
    title: "Haryana Technical Exams Package",
    description: "Complete preparation package for Haryana Technical exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "haryana",
    subcategory: "technical",
    testIds: Array.from({ length: 100 }, (_, i) => i + 301), // IDs 301-400
  },

  // Rajasthan packages
  {
    id: "pkg-rajasthan-all",
    title: "Rajasthan Complete Package",
    description: "Complete preparation package for all Rajasthan state exams with 400 comprehensive tests",
    price: 1600,
    originalPrice: 2000,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 400,
    duration: "12 months access",
    category: "rajasthan",
    testIds: Array.from({ length: 400 }, (_, i) => i + 401), // IDs 401-800
  },
  {
    id: "pkg-rajasthan-police",
    title: "Rajasthan Police Exams Package",
    description: "Complete preparation package for Rajasthan Police exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "rajasthan",
    subcategory: "police",
    testIds: Array.from({ length: 100 }, (_, i) => i + 401), // IDs 401-500
  },
  {
    id: "pkg-rajasthan-teaching",
    title: "Rajasthan Teaching Exams Package",
    description: "Complete preparation package for Rajasthan Teaching exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "rajasthan",
    subcategory: "teaching",
    testIds: Array.from({ length: 100 }, (_, i) => i + 501), // IDs 501-600
  },
  {
    id: "pkg-rajasthan-clerical",
    title: "Rajasthan Clerical Exams Package",
    description: "Complete preparation package for Rajasthan Clerical exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "rajasthan",
    subcategory: "clerical",
    testIds: Array.from({ length: 100 }, (_, i) => i + 601), // IDs 601-700
  },
  {
    id: "pkg-rajasthan-technical",
    title: "Rajasthan Technical Exams Package",
    description: "Complete preparation package for Rajasthan Technical exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "rajasthan",
    subcategory: "technical",
    testIds: Array.from({ length: 100 }, (_, i) => i + 701), // IDs 701-800
  },

  // UP packages
  {
    id: "pkg-up-all",
    title: "Uttar Pradesh Complete Package",
    description: "Complete preparation package for all UP state exams with 400 comprehensive tests",
    price: 1600,
    originalPrice: 2000,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 400,
    duration: "12 months access",
    category: "up",
    testIds: Array.from({ length: 400 }, (_, i) => i + 801), // IDs 801-1200
  },
  {
    id: "pkg-up-police",
    title: "UP Police Exams Package",
    description: "Complete preparation package for UP Police exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "up",
    subcategory: "police",
    testIds: Array.from({ length: 100 }, (_, i) => i + 801), // IDs 801-900
  },
  {
    id: "pkg-up-teaching",
    title: "UP Teaching Exams Package",
    description: "Complete preparation package for UP Teaching exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "up",
    subcategory: "teaching",
    testIds: Array.from({ length: 100 }, (_, i) => i + 901), // IDs 901-1000
  },
  {
    id: "pkg-up-clerical",
    title: "UP Clerical Exams Package",
    description: "Complete preparation package for UP Clerical exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "up",
    subcategory: "clerical",
    testIds: Array.from({ length: 100 }, (_, i) => i + 1001), // IDs 1001-1100
  },
  {
    id: "pkg-up-technical",
    title: "UP Technical Exams Package",
    description: "Complete preparation package for UP Technical exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "up",
    subcategory: "technical",
    testIds: Array.from({ length: 100 }, (_, i) => i + 1101), // IDs 1101-1200
  },

  // Central Government packages
  {
    id: "pkg-central-all",
    title: "Central Government Complete Package",
    description: "Complete preparation package for all Central Government exams with 400 comprehensive tests",
    price: 1600,
    originalPrice: 2000,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 400,
    duration: "12 months access",
    category: "central",
    testIds: Array.from({ length: 400 }, (_, i) => i + 1201), // IDs 1201-1600
  },
  {
    id: "pkg-central-ssc",
    title: "SSC Exams Package",
    description: "Complete preparation package for SSC exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "central",
    subcategory: "ssc",
    testIds: Array.from({ length: 100 }, (_, i) => i + 1201), // IDs 1201-1300
  },
  {
    id: "pkg-central-banking",
    title: "Banking Exams Package",
    description: "Complete preparation package for Banking exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "central",
    subcategory: "banking",
    testIds: Array.from({ length: 100 }, (_, i) => i + 1301), // IDs 1301-1400
  },
  {
    id: "pkg-central-railway",
    title: "Railway Exams Package",
    description: "Complete preparation package for Railway exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "central",
    subcategory: "railway",
    testIds: Array.from({ length: 100 }, (_, i) => i + 1401), // IDs 1401-1500
  },
  {
    id: "pkg-central-defense",
    title: "Defense Exams Package",
    description: "Complete preparation package for Defense exams with 100 comprehensive tests",
    price: 400,
    originalPrice: 500,
    discount: 20,
    level: "Beginner to Advanced",
    tests: 100,
    duration: "12 months access",
    category: "central",
    subcategory: "defense",
    testIds: Array.from({ length: 100 }, (_, i) => i + 1501), // IDs 1501-1600
  },
]
