// Test catalog data for government exams
export const testCatalog = {
  all: [
    // Haryana State Exams
    {
      id: 1,
      title: "Haryana Police Constable",
      description: "Complete test for Haryana Police Constable recruitment exam",
      price: 5,
      level: "Beginner to Intermediate",
      questions: 100,
      duration: 120,
      category: "haryana",
    },
    {
      id: 2,
      title: "Haryana Gram Sachiv",
      description: "Comprehensive test for Haryana Gram Sachiv exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "haryana",
    },
    {
      id: 3,
      title: "Haryana SSC Clerk",
      description: "Complete preparation for HSSC Clerk recruitment exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "haryana",
    },
    {
      id: 4,
      title: "Haryana JE Civil",
      description: "Test series for Haryana Junior Engineer (Civil) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "haryana",
    },
    {
      id: 5,
      title: "Haryana JE Electrical",
      description: "Test series for Haryana Junior Engineer (Electrical) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "haryana",
    },
    {
      id: 6,
      title: "Haryana Patwari",
      description: "Complete test for Haryana Patwari recruitment exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "haryana",
    },
    {
      id: 7,
      title: "Haryana Group D",
      description: "Comprehensive test for Haryana Group D posts",
      price: 5,
      level: "Beginner",
      questions: 100,
      duration: 90,
      category: "haryana",
    },
    {
      id: 8,
      title: "Haryana Forest Guard",
      description: "Test series for Haryana Forest Department recruitment",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "haryana",
    },
    {
      id: 9,
      title: "Haryana TGT/PGT",
      description: "Complete preparation for Haryana Teacher Eligibility exam",
      price: 5,
      level: "Advanced",
      questions: 150,
      duration: 150,
      category: "haryana",
    },
    {
      id: 10,
      title: "Haryana Police SI",
      description: "Test series for Haryana Police Sub-Inspector recruitment",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "haryana",
    },

    // Rajasthan State Exams
    {
      id: 11,
      title: "Rajasthan Police Constable",
      description: "Complete test for Rajasthan Police Constable recruitment",
      price: 5,
      level: "Beginner to Intermediate",
      questions: 100,
      duration: 120,
      category: "rajasthan",
    },
    {
      id: 12,
      title: "Rajasthan Gram Sevak",
      description: "Comprehensive test for Rajasthan Gram Sevak exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "rajasthan",
    },
    {
      id: 13,
      title: "Rajasthan LDC",
      description: "Complete preparation for RSMSSB LDC recruitment exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "rajasthan",
    },
    {
      id: 14,
      title: "Rajasthan JE Civil",
      description: "Test series for Rajasthan Junior Engineer (Civil) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "rajasthan",
    },
    {
      id: 15,
      title: "Rajasthan JE Electrical",
      description: "Test series for Rajasthan Junior Engineer (Electrical) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "rajasthan",
    },
    {
      id: 16,
      title: "Rajasthan Patwari",
      description: "Complete test for Rajasthan Patwari recruitment exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "rajasthan",
    },
    {
      id: 17,
      title: "Rajasthan Forest Guard",
      description: "Test series for Rajasthan Forest Department recruitment",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "rajasthan",
    },
    {
      id: 18,
      title: "Rajasthan REET",
      description: "Complete preparation for Rajasthan Teacher Eligibility exam",
      price: 5,
      level: "Advanced",
      questions: 150,
      duration: 150,
      category: "rajasthan",
    },
    {
      id: 19,
      title: "Rajasthan Police SI",
      description: "Test series for Rajasthan Police Sub-Inspector recruitment",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "rajasthan",
    },
    {
      id: 20,
      title: "Rajasthan Stenographer",
      description: "Comprehensive test for Rajasthan Stenographer exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "rajasthan",
    },

    // Uttar Pradesh State Exams
    {
      id: 21,
      title: "UP Police Constable",
      description: "Complete test for UP Police Constable recruitment exam",
      price: 5,
      level: "Beginner to Intermediate",
      questions: 100,
      duration: 120,
      category: "up",
    },
    {
      id: 22,
      title: "UP Lekhpal",
      description: "Comprehensive test for UP Lekhpal exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "up",
    },
    {
      id: 23,
      title: "UPSSSC PET",
      description: "Complete preparation for UP Preliminary Eligibility Test",
      price: 5,
      level: "Beginner to Intermediate",
      questions: 100,
      duration: 120,
      category: "up",
    },
    {
      id: 24,
      title: "UP JE Civil",
      description: "Test series for UP Junior Engineer (Civil) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "up",
    },
    {
      id: 25,
      title: "UP JE Electrical",
      description: "Test series for UP Junior Engineer (Electrical) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "up",
    },
    {
      id: 26,
      title: "UP VDO",
      description: "Complete test for UP Village Development Officer exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "up",
    },
    {
      id: 27,
      title: "UP TGT/PGT",
      description: "Comprehensive test for UP Teacher recruitment exam",
      price: 5,
      level: "Advanced",
      questions: 150,
      duration: 150,
      category: "up",
    },
    {
      id: 28,
      title: "UP Forest Guard",
      description: "Test series for UP Forest Department recruitment",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
      category: "up",
    },
    {
      id: 29,
      title: "UP Police SI",
      description: "Test series for UP Police Sub-Inspector recruitment",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "up",
    },
    {
      id: 30,
      title: "UP RO/ARO",
      description: "Comprehensive test for UP Review Officer exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
      category: "up",
    },
  ],

  haryana: [
    {
      id: 1,
      title: "Haryana Police Constable",
      description: "Complete test for Haryana Police Constable recruitment exam",
      price: 5,
      level: "Beginner to Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 2,
      title: "Haryana Gram Sachiv",
      description: "Comprehensive test for Haryana Gram Sachiv exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 3,
      title: "Haryana SSC Clerk",
      description: "Complete preparation for HSSC Clerk recruitment exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 4,
      title: "Haryana JE Civil",
      description: "Test series for Haryana Junior Engineer (Civil) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
    {
      id: 5,
      title: "Haryana JE Electrical",
      description: "Test series for Haryana Junior Engineer (Electrical) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
    {
      id: 6,
      title: "Haryana Patwari",
      description: "Complete test for Haryana Patwari recruitment exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 7,
      title: "Haryana Group D",
      description: "Comprehensive test for Haryana Group D posts",
      price: 5,
      level: "Beginner",
      questions: 100,
      duration: 90,
    },
    {
      id: 8,
      title: "Haryana Forest Guard",
      description: "Test series for Haryana Forest Department recruitment",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 9,
      title: "Haryana TGT/PGT",
      description: "Complete preparation for Haryana Teacher Eligibility exam",
      price: 5,
      level: "Advanced",
      questions: 150,
      duration: 150,
    },
    {
      id: 10,
      title: "Haryana Police SI",
      description: "Test series for Haryana Police Sub-Inspector recruitment",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
  ],

  rajasthan: [
    {
      id: 11,
      title: "Rajasthan Police Constable",
      description: "Complete test for Rajasthan Police Constable recruitment",
      price: 5,
      level: "Beginner to Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 12,
      title: "Rajasthan Gram Sevak",
      description: "Comprehensive test for Rajasthan Gram Sevak exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 13,
      title: "Rajasthan LDC",
      description: "Complete preparation for RSMSSB LDC recruitment exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 14,
      title: "Rajasthan JE Civil",
      description: "Test series for Rajasthan Junior Engineer (Civil) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
    {
      id: 15,
      title: "Rajasthan JE Electrical",
      description: "Test series for Rajasthan Junior Engineer (Electrical) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
    {
      id: 16,
      title: "Rajasthan Patwari",
      description: "Complete test for Rajasthan Patwari recruitment exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 17,
      title: "Rajasthan Forest Guard",
      description: "Test series for Rajasthan Forest Department recruitment",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 18,
      title: "Rajasthan REET",
      description: "Complete preparation for Rajasthan Teacher Eligibility exam",
      price: 5,
      level: "Advanced",
      questions: 150,
      duration: 150,
    },
    {
      id: 19,
      title: "Rajasthan Police SI",
      description: "Test series for Rajasthan Police Sub-Inspector recruitment",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
    {
      id: 20,
      title: "Rajasthan Stenographer",
      description: "Comprehensive test for Rajasthan Stenographer exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
  ],

  up: [
    {
      id: 21,
      title: "UP Police Constable",
      description: "Complete test for UP Police Constable recruitment exam",
      price: 5,
      level: "Beginner to Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 22,
      title: "UP Lekhpal",
      description: "Comprehensive test for UP Lekhpal exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 23,
      title: "UPSSSC PET",
      description: "Complete preparation for UP Preliminary Eligibility Test",
      price: 5,
      level: "Beginner to Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 24,
      title: "UP JE Civil",
      description: "Test series for UP Junior Engineer (Civil) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
    {
      id: 25,
      title: "UP JE Electrical",
      description: "Test series for UP Junior Engineer (Electrical) exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
    {
      id: 26,
      title: "UP VDO",
      description: "Complete test for UP Village Development Officer exam",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 27,
      title: "UP TGT/PGT",
      description: "Comprehensive test for UP Teacher recruitment exam",
      price: 5,
      level: "Advanced",
      questions: 150,
      duration: 150,
    },
    {
      id: 28,
      title: "UP Forest Guard",
      description: "Test series for UP Forest Department recruitment",
      price: 5,
      level: "Intermediate",
      questions: 100,
      duration: 120,
    },
    {
      id: 29,
      title: "UP Police SI",
      description: "Test series for UP Police Sub-Inspector recruitment",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
    {
      id: 30,
      title: "UP RO/ARO",
      description: "Comprehensive test for UP Review Officer exam",
      price: 5,
      level: "Advanced",
      questions: 120,
      duration: 120,
    },
  ],
}

// Generate a set of questions for a test
function generateQuestions(category: string, count = 5) {
  const questionSets = {
    Haryana: [
      {
        question: "हरियाणा राज्य का गठन कब हुआ था?",
        options: ["1 नवंबर 1956", "1 नवंबर 1966", "1 दिसंबर 1966", "15 अगस्त 1947"],
        correctAnswer: "1 नवंबर 1966",
      },
      {
        question: "हरियाणा का राज्य पशु कौन सा है?",
        options: ["बाघ", "सिंह", "काला हिरण", "हंस"],
        correctAnswer: "काला हिरण",
      },
      {
        question: "हरियाणा का वर्तमान राज्यपाल कौन है?",
        options: ["बंडारू दत्तात्रेय", "सत्यदेव नारायण आर्य", "कप्तान सिंह सोलंकी", "मनोहर लाल खट्टर"],
        correctAnswer: "बंडारू दत्तात्रेय",
      },
      {
        question: "हरियाणा में कुल कितने जिले हैं?",
        options: ["20", "21", "22", "23"],
        correctAnswer: "22",
      },
      {
        question: "हरियाणा की राजधानी कौन सी है?",
        options: ["चंडीगढ़", "फरीदाबाद", "गुरुग्राम", "अंबाला"],
        correctAnswer: "चंडीगढ़",
      },
      {
        question: "हरियाणा का क्षेत्रफल कितना है?",
        options: ["44,212 वर्ग किमी", "30,464 वर्ग किमी", "1,70,000 वर्ग किमी", "44,212 वर्ग किमी"],
        correctAnswer: "44,212 वर्ग किमी",
      },
      {
        question: "हरियाणा की जनसंख्या (2011 की जनगणना के अनुसार) कितनी है?",
        options: ["2.53 करोड़", "1.25 करोड़", "6.8 करोड़", "3.5 करोड़"],
        correctAnswer: "2.53 करोड़",
      },
      {
        question: "हरियाणा का राज्य पक्षी कौन सा है?",
        options: ["कबूतर", "काला तीतर", "मोर", "बाज"],
        correctAnswer: "काला तीतर",
      },
      {
        question: "हरियाणा का राज्य वृक्ष कौन सा है?",
        options: ["पीपल", "बरगद", "नीम", "पलाश"],
        correctAnswer: "पीपल",
      },
      {
        question: "हरियाणा का राज्य फूल कौन सा है?",
        options: ["कमल", "गुड़हल", "गेंदा", "गुलाब"],
        correctAnswer: "कमल",
      },
    ],
    Rajasthan: [
      {
        question: "राजस्थान राज्य का गठन कब हुआ था?",
        options: ["1 नवंबर 1956", "1 नवंबर 1966", "30 मार्च 1949", "15 अगस्त 1947"],
        correctAnswer: "30 मार्च 1949",
      },
      {
        question: "राजस्थान का राज्य पशु कौन सा है?",
        options: ["बाघ", "सिंह", "चिंकारा", "ऊंट"],
        correctAnswer: "चिंकारा",
      },
      {
        question: "राजस्थान का वर्तमान राज्यपाल कौन है?",
        options: ["कलराज मिश्र", "कल्याण सिंह", "वसुंधरा राजे", "अशोक गहलोत"],
        correctAnswer: "कलराज मिश्र",
      },
      {
        question: "राजस्थान में कुल कितने जिले हैं?",
        options: ["30", "32", "33", "34"],
        correctAnswer: "33",
      },
      {
        question: "राजस्थान की राजधानी कौन सी है?",
        options: ["जयपुर", "जोधपुर", "उदयपुर", "अजमेर"],
        correctAnswer: "जयपुर",
      },
      {
        question: "राजस्थान का क्षेत्रफल कितना है?",
        options: ["3,42,239 वर्ग किमी", "2,36,751 वर्ग किमी", "1,70,000 वर्ग किमी", "4,42,120 वर्ग किमी"],
        correctAnswer: "3,42,239 वर्ग किमी",
      },
      {
        question: "राजस्थान की जनसंख्या (2011 की जनगणना के अनुसार) कितनी है?",
        options: ["6.85 करोड़", "5.25 करोड़", "7.8 करोड़", "3.5 करोड़"],
        correctAnswer: "6.85 करोड़",
      },
      {
        question: "राजस्थान का राज्य पक्षी कौन सा है?",
        options: ["गोडावण", "मोर", "कबूतर", "बाज"],
        correctAnswer: "गोडावण",
      },
      {
        question: "राजस्थान का राज्य वृक्ष कौन सा है?",
        options: ["खेजड़ी", "नीम", "पीपल", "बरगद"],
        correctAnswer: "खेजड़ी",
      },
      {
        question: "राजस्थान का राज्य फूल कौन सा है?",
        options: ["रोहिड़ा", "गुलाब", "कमल", "गेंदा"],
        correctAnswer: "रोहिड़ा",
      },
    ],
    "Uttar Pradesh": [
      {
        question: "उत्तर प्रदेश राज्य का गठन कब हुआ था?",
        options: ["1 नवंबर 1956", "1 अप्रैल 1937", "26 जनवरी 1950", "15 अगस्त 1947"],
        correctAnswer: "1 अप्रैल 1937",
      },
      {
        question: "उत्तर प्रदेश का राज्य पशु कौन सा है?",
        options: ["बाघ", "सिंह", "बारहसिंगा", "हंस"],
        correctAnswer: "बारहसिंगा",
      },
      {
        question: "उत्तर प्रदेश का वर्तमान राज्यपाल कौन है?",
        options: ["आनंदीबेन पटेल", "राम नाईक", "योगी आदित्यनाथ", "अखिलेश यादव"],
        correctAnswer: "आनंदीबेन पटेल",
      },
      {
        question: "उत्तर प्रदेश में कुल कितने जिले हैं?",
        options: ["70", "75", "80", "85"],
        correctAnswer: "75",
      },
      {
        question: "उत्तर प्रदेश की राजधानी कौन सी है?",
        options: ["लखनऊ", "कानपुर", "प्रयागराज", "वाराणसी"],
        correctAnswer: "लखनऊ",
      },
      {
        question: "उत्तर प्रदेश का क्षेत्रफल कितना है?",
        options: ["2,43,290 वर्ग किमी", "3,42,239 वर्ग किमी", "1,70,000 वर्ग किमी", "4,42,120 वर्ग किमी"],
        correctAnswer: "2,43,290 वर्ग किमी",
      },
      {
        question: "उत्तर प्रदेश की जनसंख्या (2011 की जनगणना के अनुसार) कितनी है?",
        options: ["19.98 करोड़", "6.85 करोड़", "12.5 करोड़", "23.4 करोड़"],
        correctAnswer: "19.98 करोड़",
      },
      {
        question: "उत्तर प्रदेश का राज्य पक्षी कौन सा है?",
        options: ["सारस क्रेन", "मोर", "कबूतर", "बाज"],
        correctAnswer: "सारस क्रेन",
      },
      {
        question: "उत्तर प्रदेश का राज्य वृक्ष कौन सा है?",
        options: ["अशोक", "नीम", "पीपल", "बरगद"],
        correctAnswer: "अशोक",
      },
      {
        question: "उत्तर प्रदेश का राज्य फूल कौन सा है?",
        options: ["पलाश", "गुलाब", "कमल", "गेंदा"],
        correctAnswer: "पलाश",
      },
    ],
  }

  // Get the appropriate question set
  const questions = questionSets[category as keyof typeof questionSets] || questionSets["Haryana"]

  // Create an array of questions with IDs
  return questions.slice(0, count).map((q, index) => ({
    id: index + 1,
    ...q,
  }))
}

// Generate test data for all tests
function generateTestData() {
  const testData: Record<number, any> = {}

  // Generate Haryana tests (1-50)
  for (let i = 1; i <= 50; i++) {
    testData[i] = {
      title: `Haryana Test ${i}`,
      description: `Comprehensive test for Haryana state exam preparation`,
      duration: 60 + (i % 4) * 30, // Between 60-150 minutes
      questions: generateQuestions("Haryana", 5 + (i % 5)), // Between 5-9 questions
    }
  }

  // Generate Rajasthan tests (51-100)
  for (let i = 51; i <= 100; i++) {
    testData[i] = {
      title: `Rajasthan Test ${i - 50}`,
      description: `Comprehensive test for Rajasthan state exam preparation`,
      duration: 60 + (i % 4) * 30, // Between 60-150 minutes
      questions: generateQuestions("Rajasthan", 5 + (i % 5)), // Between 5-9 questions
    }
  }

  // Generate UP tests (101-150)
  for (let i = 101; i <= 150; i++) {
    testData[i] = {
      title: `UP Test ${i - 100}`,
      description: `Comprehensive test for Uttar Pradesh state exam preparation`,
      duration: 60 + (i % 4) * 30, // Between 60-150 minutes
      questions: generateQuestions("Uttar Pradesh", 5 + (i % 5)), // Between 5-9 questions
    }
  }

  return testData
}

// Export the test data
export const testData = generateTestData()
